name = "PUPM"
uuid = "98242e13-4771-4396-83d3-ad6bca37f0e8"
version = "1.0.0-DEV"
authors = ["Aminofa70 <amin.alibakhshi@upm.es> and contributors"]

[deps]
FIGlet = "3064a664-84fe-4d92-92c7-ed492f3d8fae"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
FIGlet = "0.2.2"
Ferrite = "1.0.0"
Revise = "3.6.4"
Tensors = "1.16.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
